# b站上传线路选择，默认为自动模式，目前可手动切换为bda2, kodo, ws, qn, cos, cos-internal(支持腾讯云内网免流+提速)
lines = "AUTO"
# 单文件并发上传数，未达到带宽上限时增大此值可提高上传速度
threads = 3
# 检测到主播下播后延迟再次检测，单位：秒，避免特殊情况提早启动上传导致漏录
delay = 10
# 检测间隔时间，单位：秒
event_loop_interval = 40

# 自定义标题的时间格式, {title}代表直播间标题, {time}代表年-月-日, {name}代表主播名字
title = "【狼宝滴录播】 {time} {title}"
tid = 65 # 投稿分区码
copyright = 2 # 1为自制
cover_path = "/cover/up.jpg"
# 支持strftime, {title}占位符。 希望你可以保留软件出处
description = """
血狼的录播
我滴狼宝~~~~
感谢 @司瑁瑁 提供的录播封面
"""
dynamic = ""
# dtime = 14_400 # 设置延时发布时间，距离提交大于2小时，格式为时间戳
uploader = "biliup-rs"  # 覆盖全局默认上传插件，Noop为不上传，但会执行后处理
user_cookie = "cookies.json" # 使用指定的账号上传
tags = [ "明日方舟", "娱乐" , "录播", "搞笑"]