base:
  rec-dir:
  workers: 2

  server:
    port: 5000
    webhooks: webhook
    time_cache_path: cache/time.json
    video_cache_path: cache/video.json


  process:
    danmaku: false
    video_process_dir: video_process
    video_process_ext: [ "mp4", "flv", "mkv" ]
    video_process_danmaku: true

  bilibili-upload:
    enable: false
    multipart: 2
    delete-after-upload: true
    auto-upload: true
    min-time: 1

  rclone-upload:
    enable: true
    delete-after-upload: true
    remote:

  proxy:
    enable: true
    proxy-url: http://127.0.0.1:10809

notify:
  telegram:
    enable: true
    bot-token:
    chat-id:

account:
  credential:
    sessdata:
    bili_jct:
    buvid3: